---
language: node_js
node_js: stable
sudo: false
dist: trusty

addons:
  chrome: stable

cache: yarn

env:
  global:
    - JOBS=1

jobs:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

  include:
    - stage: "Tests"
      before_install:
        - npm install -g codecov
        - npm install -g @commitlint/travis-cli
        - yarn --version
      script:
        - commitlint-travis
        - npm run lint
        - npm test
      after_success:
        - codecov --file=coverage/node/lcov.info
        - codecov --file=coverage/ember/lcov.info

    - stage: "Regression Tests"
      env: EMBER_TRY_SCENARIO=ember-release
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-canary
    - env: EMBER_TRY_SCENARIO=ember-default-with-jquery

    - stage: "Release"
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release

before_install:
  - yarn --version

script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO

stages:
  - "Tests"
  - "Regression Tests"
  - name: "Release"
    if: branch = master

